### ISSUE TITLE
Support for CockroachDB

### ISSUE THREAD

**Issue by aaomidi** [hashicorp/cdktf-provider-postgresql#492]
Hi!

I did not see any documentation other than https://github.com/hashicorp/terraform-provider-postgresql/issues/91 for terraform to support a cockroachdb backend. I was wondering if this project has support for cockroachdb, or if there's something I need to do.

Based on the answers here, I'll do a followup PR to add documentation to https://www.terraform.io/language/settings/backends/pg

**Comment by DanielMSchmidt** [comment]
Hey there, I asked the maintainer of the postgresql provider and they said it's not tested, but if one sets the `expected_version` so that the provider does not fail detecting the version it could work. Hope this helps, let me know if it worked :)

**Comment by ansgarm** [comment]
Hey @aaomidi, how did it go?

**Comment by DanielMSchmidt** [comment]
Closed due to inactivity
